/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdresseDto } from './adresseDto';


export interface EntrepriseDto { 
    id?: number;
    nom?: string;
    description?: string;
    adresse?: AdresseDto;
    codeFiscal?: string;
    photo?: string;
    email?: string;
    numTel?: string;
    siteWeb?: string;
}

