/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VentesDto } from './ventesDto';
import { ArticleDto } from './articleDto';


export interface LigneVenteDto { 
    id?: number;
    vente?: VentesDto;
    quantite?: number;
    prixUnitaire?: number;
    article?: ArticleDto;
    entrepriseId?: number;
}

