/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommandeFournisseurDto } from './commandeFournisseurDto';
import { ArticleDto } from './articleDto';


export interface LigneCommandeFournisseurDto { 
    id?: number;
    article?: ArticleDto;
    commandeFournisseur?: CommandeFournisseurDto;
    quantite?: number;
    prixUnitaire?: number;
    entrepriseId?: number;
}

