/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleDto } from './articleDto';


export interface MvtStockDto { 
    id?: number;
    dateMvt?: string;
    quantite?: number;
    article?: ArticleDto;
    typeMvtStock?: MvtStockDto.TypeMvtStockEnum;
    entrepriseId?: number;
    sourceMvtStock?: MvtStockDto.SourceMvtStockEnum;
}
export namespace MvtStockDto {
    export const TypeMvtStockEnum = {
        Entree: 'ENTREE',
        Sortie: 'SORTIE',
        CorrectionPos: 'CORRECTION_POS',
        CorrectionNeg: 'CORRECTION_NEG'
    } as const;
    export type TypeMvtStockEnum = typeof TypeMvtStockEnum[keyof typeof TypeMvtStockEnum];
    export const SourceMvtStockEnum = {
        CommandeClient: 'COMMANDE_CLIENT',
        CommandeFournisseur: 'COMMANDE_FOURNISSEUR',
        Vente: 'VENTE'
    } as const;
    export type SourceMvtStockEnum = typeof SourceMvtStockEnum[keyof typeof SourceMvtStockEnum];
}


