/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntrepriseDto } from './entrepriseDto';
import { RolesDto } from './rolesDto';
import { AdresseDto } from './adresseDto';


export interface UtilisateurDto { 
    id?: number;
    nom?: string;
    prenom?: string;
    email?: string;
    dateDeNaissance?: string;
    motDePasse?: string;
    adresse?: AdresseDto;
    photo?: string;
    entreprise?: EntrepriseDto;
    roles?: Array<RolesDto>;
    entrepriseId?: number;
}

