/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneVenteDto } from './ligneVenteDto';


export interface VentesDto { 
    id?: number;
    code?: string;
    dateVente?: string;
    commentaire?: string;
    entrepriseId?: number;
    ligneVenteDtos?: Array<LigneVenteDto>;
}

