export * from './articles.service';
import { ArticlesService } from './articles.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './catgories.service';
import { CatgoriesService } from './catgories.service';
export * from './clientController.service';
import { ClientControllerService } from './clientController.service';
export * from './commandeClientController.service';
import { CommandeClientControllerService } from './commandeClientController.service';
export * from './commandeFournisseurController.service';
import { CommandeFournisseurControllerService } from './commandeFournisseurController.service';
export * from './entrepriseController.service';
import { EntrepriseControllerService } from './entrepriseController.service';
export * from './fournisseurController.service';
import { FournisseurControllerService } from './fournisseurController.service';
export * from './mvmtStockController.service';
import { MvmtStockControllerService } from './mvmtStockController.service';
export * from './photoController.service';
import { PhotoControllerService } from './photoController.service';
export * from './utilisateurController.service';
import { UtilisateurControllerService } from './utilisateurController.service';
export * from './ventesController.service';
import { VentesControllerService } from './ventesController.service';
export const APIS = [ArticlesService, AuthControllerService, CatgoriesService, ClientControllerService, CommandeClientControllerService, CommandeFournisseurControllerService, EntrepriseControllerService, FournisseurControllerService, MvmtStockControllerService, PhotoControllerService, UtilisateurControllerService, VentesControllerService];
